backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

local_backend: true

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Pages"
    files:
      - name: "footer"
        label: "Footer & Header"
        file: "content/pages/footer.md"
        fields: 
          - {
              label: Footer Background Image,
              name: image,
              widget: image,
          }
      - name: "home"
        label: "Home Page"
        file: "content/pages/home.md"
        fields:
          - {
              label: Introduction,
              name: introduction,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: Introduction,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["dark-mode"],
                  },
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    default: Who We Are,
                  },
                  { label: Background Image, name: image, widget: image},
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Strategy,
              name: strategy,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: Strategy,
                  },
                  {
                    label: Page 1,
                    name: page_1,
                    widget: object,
                    fields:
                      [
                        {
                          label: Title,
                          name: title,
                          widget: string,
                          default: Who We Are,
                        },
                        {
                          label: Section Background & Colour Scheme,
                          name: mode,
                          widget: select,
                          multiple: false,
                          options:
                            [
                              { label: "Light/no image - white background", value: "dark-mode" },
                              { label: "Dark - image background", value: "light-mode" },
                              { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                            ],
                          default: ["light-mode"],
                        },
                        { label: Body, name: body, widget: markdown },
                      ]
                  },
                  {
                    label: Page 2,
                    name: page_2,
                    widget: object,
                    fields:
                      [
                        {
                          label: Statement,
                          name: statement,
                          widget: text,
                          default: Who We Are,
                        },
                        {
                          label: Section Background & Colour Scheme,
                          name: mode,
                          widget: select,
                          multiple: false,
                          options:
                            [
                              { label: "Light/no image - white background", value: "dark-mode" },
                              { label: "Dark - image background", value: "light-mode" },
                              { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                            ],
                          default: ["dark-mode"],
                        },
                        { label: Bullet Point List, name: bullets, widget: list, allow_add: true, fields: 
                          [
                            {
                              label: Icon, name: icon, widget: string
                            },
                            {
                              label: Body, name: body, widget: text
                            },
                          ]
                        },
                        { label: Body, name: body, widget: markdown },
                      ]
                  },
                  { label: Background Image, name: image, widget: image},
                  { label: Button, name: button, widget: object, fields: 
                    [
                      { label: Label, name: label, widget: string, default: Learn More },
                      { label: Destination, name: link, widget: string, default: /about },
                    ]
                  }
                ],
            }
          - {
              label: News,
              name: news,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: News,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["light-mode"],
                  },
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    default: Who We Are,
                    required: false,
                  },
                  { label: Background Image, name: image, widget: image },
                  { label: Body, name: body, widget: markdown, required: false },
                  { label: Contact Link, name: contact, widget: object, fields: 
                    [
                      { label: Label, name: label, widget: string, default: media@irbisio.com },
                      { label: Destination, name: link, widget: string, default: media@irbisio.com },
                    ]
                  }
                ],    
            }
          - {
              label: About,
              name: about,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: About,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["dark-mode"],
                  },
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    default: Who We Are,
                  },
                  { label: Background Image, name: image, widget: image},
                  { label: Body, name: body, widget: markdown },
                  { label: Button, name: button, widget: object, fields: 
                    [
                      { label: Label, name: label, widget: string, default: Learn More },
                      { label: Destination, name: link, widget: string, default: /about },
                    ]
                  }
                ],    
            }
          - {
              label: Snow Leopard,
              name: leopard,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: Wild Cat Rescue Fund,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["snow-mode"],
                  },
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    default: Who We Are,
                  },
                  { label: Background Image, name: image, widget: image},
                  { label: Body, name: body, widget: markdown },
                  { label: Foundation Button, name: button, widget: object, fields: 
                    [
                      { label: Label, name: label, widget: string, default: Track the Snow Leopard },
                      { label: Destination, name: link, widget: string, default: /about },
                    ]
                  }
                ],    
            }
      - name: "about"
        label: "About Page"
        file: "content/pages/about.md"
        fields:
          - {
              label: About Us,
              name: about,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: About,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["dark-mode"],
                  },
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    default: Who We Are,
                  },
                  {
                    label: Sub - Title,
                    name: sub_title,
                    widget: string,
                    default: Who We Are,
                    required: false,
                  },
                  { label: Body, name: body, widget: markdown },
                  { label: Background Image, name: image, widget: image},
                ],
            }
          - {
              label:  Partner Section,
              name: partners,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: Partners,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["dark-mode"],
                  },
                  { label: Partner Details, name: details, widget: object, allow_add: true, fields: 
                    [
                      { label: Partner Logo, name: logo, widget: image },
                      { label: Partner Link (their site?), name: button, widget: object, fields: 
                        [
                          { label: Label, name: label, widget: string, default: Learn More },
                          { label: Destination, name: link, widget: string, default: /about },
                        ]
                      },
                      { label: Body, name: body, widget: markdown },
                    ]
                  },
                  { label: Background Image, name: image, widget: image},
                ],
            }
          - {
              label:  Team Section,
              name: team,
              widget: object,
              summary: "{{fields.section}}",
              fields:
                [
                  {
                    label: Section Name,
                    name: section,
                    widget: string,
                    default: Team,
                  },
                  {
                    label: Section Background & Colour Scheme,
                    name: mode,
                    widget: select,
                    multiple: false,
                    options:
                      [
                        { label: "Light/no image - white background", value: "dark-mode" },
                        { label: "Dark - image background", value: "light-mode" },
                        { label: "Light, with image, (ala Snow Leopard)", value: "snow-mode" },
                      ],
                    default: ["dark-mode"],
                  },
                  { label: Team Member, name: member, widget: object, allow_add: true, fields: 
                    [
                      { label: Team Photo, name: photo, widget: image },
                      { label: Name, name: name, widget: string },
                      { label: Title, name: title, widget: string },
                      { label: Body, name: body, widget: markdown },
                    ]
                  },
                  { label: Background Image, name: image, widget: image},
                ],
            }

  - name: "posts"
    label: "News"
    folder: "content/news/"
    create: true
    path: "{{slug}}/index"
    fields:
      - {
          label: "CMS Key",
          name: "cms",
          widget: "hidden",
          default: "news",
        }
      - { label: "Hrading", name: "heading", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
